### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by igoralvarezz** [mir-aidj/all-in-one#3]
Great job with the paper! Have been testing and it works really well. 
Any chance of sharing a traning code example/guide?

Thanks in advance

**Comment by tae-jun** [comment]
Hi, I have a plan to release the code for training in a month.

Please wait a bit! Thanks :)

**Comment by tae-jun** [comment]
The training code has just been added. Please check [here](https://github.com/mir-aidj/all-in-one/blob/main/TRAINING.md)!
